language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - opam
    - ocaml-native-compilers
install: sh -ex ./autoconf/travis-install.sh
cache:
  directories:
  - ${HOME}/.opam
script: sh -ex ./autoconf/travis-ci.sh
env:
  - OCAML_VERSION=system
  - OCAML_VERSION=3.12.1
  - OCAML_VERSION=4.01.0
  - OCAML_VERSION=4.02.1
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
